language: python
python:
  - "2.7"

jobs:
  include:
    - stage: build
      script: 'pip install -r requirements.txt'

    - stage: deploy
      script: 'pip install shipa-ci && shipa-ci --app=bruno-ci --server=$SHIPASERVER --email=$SHIPAEMAIL --password=$SHIPAPASSWORD --verbose'
